config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#show'
  

  resources :posts do
    resources :comments
  end

  resources :bios
  devise_for :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bio.rb
class Bio < ApplicationRecord
  belongs_to :user
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
  has_one :bio
end

app/models/userpost.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, except: [:new]

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  private
    def set_account
      @account = current_user
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/bios_controller.rb
class BiosController < ApplicationController
  before_action :set_bio, only: [:show, :update, :edit, :destroy]
  def index
    @bios = current_user.bios
  end
  def show
  end
  def new
    @bio = Bio.new
    render partial: "form"
  end
  def edit
    render partial: "form"
  end
  def create
    @bio = Bio.new(bio_params)
    @bio.user = current_user
    if @bio.save
      flash[:success] = "New Bio successfully added!"
      redirect_to bio_path(@bio)
    else
      flash[:alert] = "There was an error adding your trip. Please try agian."
      render partial: "form"
    end
  end
  def update
    if @bio.update(bio_params)
      flash[:success] = "Bio successfully updated!"
      redirect_to bio_path(@bio)
    else
      flash[:alert] = "There was an error editing your bio. Please try agian."
      render partial: "form"
    end
  end
  def destroy
    @bio.destroy
    flash[:success] = "Bio successfully deleted!"
    redirect_to bios_path
  end
  private
    def set_bio
      @bio = current_user.bio
    end
    def set_account
      current_user.bio
    end
    def bio_params
      params.require(:bio).permit(:avatar, :description)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: [:edit, :update, :destroy]

  def new
    @comment = @post.comments.new
    render partial: "form"
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @comment.update(comment_params)
      redirect_to post_path(@path)
    else
      render partial: "form"
    end
  end

  def destroy
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
    def set_post
      @post = Post.find(params[:post_id])
    end

    def set_comment
      @comment = @post.comments.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:message)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :set_post, only: [:show, :update, :edit, :destroy]
# before_action :set_user

  def index
    @posts = current_user.posts
  end

  def show
    @comments = @post.comments.all
  end

  def new
    @post = Post.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to @post
    else
      render partial: "form"
    end
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render partial: "form"
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private
    def set_post
      @post = current_user.posts.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:content)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def show
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/accountss_helper.rb
module AccountssHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/accounts/show.html.erb
<h1>Test</h1>
<%= link_to 'New Bio', new_bio_path %>

app/views/bios/_form.html.erb
<%= stylesheet_link_tag "application" %>
<div class="ui container">
  <h1 class="ui header"><%= current_user.id ? 'Edit Bio' : 'Create Bio' %></h1>
    <%= form_for @bio do |f| %>
      <div class="ui form" id="trip_form">
        <%= f.label :description %>
        <%= f.text_area :description %>
        <%= f.submit nil, class: "ui button primary" %>
    </div>
  <% end %>
</div>

app/views/bios/_show.html.erb
<%= @bio.description %>

app/views/bios/index.html.erb
<div class="ui container">
  <div class="ui header">
    <h1>My Bios</h1>
    <%= link_to "Create New Bio", new_account_bio_path, class: "ui button primary" %>
  </div>
  <div class="sixteen wide mobile eight wide tablet four wide computer column">
    <div class="ui cards">
            <div class="ui three buttons">
              <%= link_to "Show", bio, class: "ui green button" %>
              <%= link_to "Edit", edit_bio_path(bio), class: "ui yellow button"  %>
              <%= link_to "Destroy", bio, method: :delete, class: "ui red button", data: {confirm: "Are you sure?"} %>
            </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bios/new.html.erb
<h1>Bios#new</h1>
<p>Find me in app/views/bios/new.html.erb</p>

app/views/bios/show.html.erb
<%= stylesheet_link_tag "application" %>

<div class="ui button">
    <%= link_to 'New Bio', new_bio_path %>
</div>

<div class="ui button">
  <%= link_to 'Edit Bio', edit_bio_path %>
</div>

<div class="container segment">
    <%= @bio.description %>
  </div>

app/views/comments/_comment.html.erb
<hr>
<p><%= comment.message %></p>
<hr>

app/views/comments/_form.html.erb
<h1><%= @comment.id ? 'Edit Comment' : 'Create Comment' %></h1>
<hr>
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :message %>
  <%= f.text_field :message, required: true, autofocus: true %>
  <br>
  <%= f.submit %>
<% end %>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/_navbar.html.erb
  <div class="ui segment" style="background-color: #0066cc">
    <div class="ui secondary menu">
      <div class="item">
        <%= link_to 'Home', root_path, class: "ui button" %>
      </div>
      <div class="item">
        <%= link_to 'Posts', posts_path, class: "ui button" %>
      </div>
      <div class="item">
        <%= link_to 'Bio', bio_path([:id]), class: "ui button" %>
      </div>
      <div class="right menu">
        <div class="ui item">
          <%= link_to 'Logout', destroy_user_session_path, class: "ui button", method: :delete %>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackathon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <% if content_for?(:head) %>
    <%= yield(:head) %>
<% end %> 

  </head>

  <body>
  <%= render(partial: 'layouts/navbar') %>
  <div class="ui container center aligned">
    <%= yield %>
  </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= stylesheet_link_tag "application" %>

<div class="ui container center aligned">
  <h1><%= @post.id ? 'Edit Post' : 'Create Post' %></h1>

    <div class="ui form">
      <%= form_for @post do |f| %>
        <%= f.label :content, class: "ui left aligned container" %>
        <%= f.text_field :content, required: true, autofocus: true %>
        <%= f.submit nil, class: "ui button" %>
      <% end %>
    </div>
</div>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<<<<<<< HEAD
<%= link_to 'Create a New Post', new_post_path %>
<hr >

  <div class="ui feed">
    <% @posts.each do |post| %>
    
    <div class="ui segment">
      <div class="content">
        <h2 class="ui left aligned container"><%= link_to post.content, post_path(post) %></h2>
        <div class="ui left aligned container">
          <a class="like">
            <i class="like icon"></i> Nobody has liked this post!
          </a>
        </div>
      </div>
      <div class="ui container">
        <button class="ui button left aligned">Like <i class="heart icon"></i></button>
        <%= link_to 'Edit <i class="edit icon"></i>'.html_safe, edit_post_path(post), class: "ui button center aligned" %>
        <%= link_to 'Delete <i class="trash icon"></i>'.html_safe, post_path(post), class: "ui button right aligned", method: :delete %>
      </div>
    </div>
   
    <% end %>

  </div>
</div>  
=======
<%= link_to 'Create a New Post', new_post_path, class: "mini ui teal button" %>
<hr>
<% @posts.each do |post| %>
    <h2><%= link_to post.content, post_path(post) %></h2>
    <%= link_to 'Delete', post, method: :delete, class: "mini ui red button" %>
  <hr>
<% end %>
>>>>>>> fixed edit delete

app/views/posts/show.html.erb
<h1><%= @post.content %></h1>
<<<<<<< HEAD
<%= link_to 'Edit Post', edit_post_path(@post), class: "ui button" %>
<%= link_to 'Delete Post', @post, class: "ui button", method: :delete %>
<%= link_to 'Back to Posts', posts_path, class: "ui button" %>
<%= link_to 'Add Comment', new_post_comment_path(@post), class: "ui button" %>
  <% @comments.each do |comment| %>
  <hr>
  <p><%= comment.message %></p>
  <hr>
  
<% end %>


=======
<%= link_to 'Add Comment', new_post_comment_path(@post), class: "mini ui teal button" %>
<% @comments.each do |comment| %>
<hr>
<p style="font-size: x-large"><%= comment.message %></p>
<%= link_to 'Edit', edit_post_comment_path(@post), class: "mini ui grey button" %>
<%= link_to 'Delete', post_comment_path(@post, comment), method: :delete, class: "mini ui red button" %>
<% end %>
>>>>>>> fixed edit delete

app/views/static_pages/show.html.erb
<h1 class="ui header">Welcome to TwitterGram!</h1>

<img class="ui middle aligned large rounded image" src="http://cdn.ilovefreesoftware.com/wp-content/uploads/2009/09/TwitterGram.png">
 <body style="background-color: #e6ffff">
 </body>